// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// getPositions
std::vector<std::vector<size_t>> getPositions(size_t numOfGenes, size_t numOfOriginalCells, std::string countMatFilename);
RcppExport SEXP _fishpond_getPositions(SEXP numOfGenesSEXP, SEXP numOfOriginalCellsSEXP, SEXP countMatFilenameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< size_t >::type numOfGenes(numOfGenesSEXP);
    Rcpp::traits::input_parameter< size_t >::type numOfOriginalCells(numOfOriginalCellsSEXP);
    Rcpp::traits::input_parameter< std::string >::type countMatFilename(countMatFilenameSEXP);
    rcpp_result_gen = Rcpp::wrap(getPositions(numOfGenes, numOfOriginalCells, countMatFilename));
    return rcpp_result_gen;
END_RCPP
}
// getExpression
std::vector<std::vector<float>> getExpression(size_t numOfGenes, size_t numOfOriginalCells, std::vector<std::vector<size_t>>& positions, std::string countMatFilename);
RcppExport SEXP _fishpond_getExpression(SEXP numOfGenesSEXP, SEXP numOfOriginalCellsSEXP, SEXP positionsSEXP, SEXP countMatFilenameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< size_t >::type numOfGenes(numOfGenesSEXP);
    Rcpp::traits::input_parameter< size_t >::type numOfOriginalCells(numOfOriginalCellsSEXP);
    Rcpp::traits::input_parameter< std::vector<std::vector<size_t>>& >::type positions(positionsSEXP);
    Rcpp::traits::input_parameter< std::string >::type countMatFilename(countMatFilenameSEXP);
    rcpp_result_gen = Rcpp::wrap(getExpression(numOfGenes, numOfOriginalCells, positions, countMatFilename));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_fishpond_getPositions", (DL_FUNC) &_fishpond_getPositions, 3},
    {"_fishpond_getExpression", (DL_FUNC) &_fishpond_getExpression, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_fishpond(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
