# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getPositions <- function(numOfGenes, numOfOriginalCells, countMatFilename) {
    .Call('_fishpond_getPositions', PACKAGE = 'fishpond', numOfGenes, numOfOriginalCells, countMatFilename)
}

getExpression <- function(numOfGenes, numOfOriginalCells, positions, countMatFilename) {
    .Call('_fishpond_getExpression', PACKAGE = 'fishpond', numOfGenes, numOfOriginalCells, positions, countMatFilename)
}

